version: "3.8"
services:
  db:
    image: postgres:17.1
    container_name: kanban-db
    ports:
      - 5434:5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/kanban
      - POSTGRES_DB=kanban
      - POSTGRES_PASSWORD=password
volumes:
  db:
networks:
  backend:
